# Generated by Django 5.2.17 on 2026-09-04 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsCommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('BIKE', 'Bike / Scooter (Small items)'), ('AUTO', 'Auto Rickshaw (Medium cargo)'), ('CAR', 'Car / Van (Delicate equipment)'), ('MINI_TRUCK', 'Mini Truck / Pickup (Furniture/Appliances)'), ('TRUCK', 'Truck (Heavy cargo / bulk)'), ('SPECIAL_TRANSPORT', 'Specialized Transport')], max_length=30, unique=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('minimum_fee', models.DecimalField(decimal_places=2, default=20.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField()),
                ('pickup_city', models.CharField(max_length=100)),
                ('pickup_pincode', models.CharField(max_length=20)),
                ('dropoff_address', models.TextField()),
                ('dropoff_city', models.CharField(max_length=100)),
                ('dropoff_pincode', models.CharField(max_length=20)),
                ('pickup_otp', models.CharField(blank=True, max_length=6)),
                ('delivery_otp', models.CharField(blank=True, max_length=6)),
                ('status', models.CharField(choices=[('PENDING_DISPATCH', 'Pending Driver Dispatch'), ('ACCEPTED', 'Driver Assigned / Accepted'), ('ARRIVED_AT_PICKUP', 'Driver Arrived at Pickup'), ('PICKED_UP', 'Asset Picked Up & In-Transit'), ('DELIVERED', 'Delivered to Customer'), ('CANCELLED', 'Delivery Cancelled')], default='PENDING_DISPATCH', max_length=30)),
                ('transport_fee', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('driver_payout', models.DecimalField(decimal_places=2, default=135.0, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=15.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_assigned', to=settings.AUTH_USER_MODEL)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_order', to='rentals.rental')),
            ],
            options={
                'verbose_name': 'Delivery Order',
                'verbose_name_plural': 'Delivery Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransportProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('BEFORE_LOADING', 'Before Loading (Owner Location)'), ('PICKUP_CONFIRMED', 'Asset Loaded & Secured'), ('IN_TRANSIT', 'In-Transit Check'), ('DELIVERY_COMPLETED', 'Unloaded & Handed Over (Customer Location)')], max_length=30)),
                ('image', models.ImageField(upload_to='logistics/proofs/')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_proofs', to='logistics.deliveryorder')),
            ],
            options={
                'verbose_name': 'Transport Proof',
                'verbose_name_plural': 'Transport Proofs',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('BIKE', 'Bike / Scooter (Small items)'), ('AUTO', 'Auto Rickshaw (Medium cargo)'), ('CAR', 'Car / Van (Delicate equipment)'), ('MINI_TRUCK', 'Mini Truck / Pickup (Furniture/Appliances)'), ('TRUCK', 'Truck (Heavy cargo / bulk)'), ('SPECIAL_TRANSPORT', 'Specialized Transport')], default='BIKE', max_length=30)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('make_model', models.CharField(help_text='e.g. Tata Ace, Mahindra Bolero', max_length=100)),
                ('max_payload_kg', models.DecimalField(decimal_places=2, default=50.0, max_digits=8)),
                ('cargo_volume_cbm', models.DecimalField(decimal_places=2, default=0.5, help_text='Cubic meters capacity', max_digits=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='logistics.vehicle'),
        ),
    ]
