# Generated by Django 5.2.17 on 2026-09-04 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ESCROW_RELEASED', 'Security Deposit Escrow Released'), ('ESCROW_DEDUCTED', 'Damage Deduction from Escrow'), ('DISPUTE_ARBITRATED', 'Admin Arbitrated Dispute'), ('ASSET_VERIFIED', 'Physical Asset Verified by Admin'), ('ASSET_REJECTED', 'Physical Asset Rejected by Admin'), ('REFUND_ISSUED', 'Manual Refund Issued'), ('USER_ROLE_GRANTED', 'Administrative Role Granted'), ('SYSTEM_CONFIG_UPDATED', 'System Configuration Modified')], db_index=True, max_length=50)),
                ('target_model', models.CharField(db_index=True, max_length=50)),
                ('target_id', models.CharField(db_index=True, max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_authored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
