# Generated by Django 5.2.17 on 2026-09-04 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App Notification'), ('EMAIL', 'Email'), ('SMS', 'SMS Text Message'), ('PUSH', 'Mobile Push Notification')], default='IN_APP', max_length=20)),
                ('notification_type', models.CharField(choices=[('RENTAL_BOOKED', 'Rental Booking Created'), ('RENTAL_CONFIRMED', 'Rental Confirmed & Paid'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('HANDOVER_OTP', 'Handover Verification OTP'), ('RETURN_REMINDER', 'Return Window Approaching'), ('OVERDUE_WARNING', 'Rental Overdue Warning'), ('INSPECTION_FLAGGED', 'Inspection Discrepancy Found'), ('DAMAGE_REPORTED', 'Damage Report Filed'), ('QUOTE_RECEIVED', 'Repair Quote Submitted'), ('QUOTE_ACCEPTED', 'Repair Quote Accepted'), ('EXTENSION_REQUESTED', 'Rental Extension Requested'), ('EXTENSION_RESOLVED', 'Rental Extension Decision'), ('REVIEW_RECEIVED', 'New Review Received'), ('TRUST_SCORE_UPDATE', 'Trust Score & Tier Update'), ('SYSTEM_ALERT', 'System Alert')], default='SYSTEM_ALERT', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Contextual metadata payload')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
