# Generated by Django 5.2.17 on 2026-09-04 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('inspections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CAMERA_REPAIR', 'Camera & Lens Repair'), ('LAPTOP_REPAIR', 'Laptop & Computer Repair'), ('BIKE_SERVICE', 'Bike & Two-Wheeler Service'), ('FURNITURE_REPAIR', 'Furniture Restoration & Carpentry'), ('GAMING_REPAIR', 'Gaming Console & Controller Repair'), ('CLEANING', 'Sanitization & Deep Cleaning'), ('MAINTENANCE', 'Preventative Maintenance'), ('ELECTRONICS', 'General Electronics Repair')], max_length=40, unique=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CAMERA_REPAIR', 'Camera & Lens Repair'), ('LAPTOP_REPAIR', 'Laptop & Computer Repair'), ('BIKE_SERVICE', 'Bike & Two-Wheeler Service'), ('FURNITURE_REPAIR', 'Furniture Restoration & Carpentry'), ('GAMING_REPAIR', 'Gaming Console & Controller Repair'), ('CLEANING', 'Sanitization & Deep Cleaning'), ('MAINTENANCE', 'Preventative Maintenance'), ('ELECTRONICS', 'General Electronics Repair')], default='ELECTRONICS', max_length=40)),
                ('business_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('experience_years', models.IntegerField(default=1)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('base_diagnostic_fee', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Provider',
                'verbose_name_plural': 'Service Providers',
                'ordering': ['-rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CAMERA_REPAIR', 'Camera & Lens Repair'), ('LAPTOP_REPAIR', 'Laptop & Computer Repair'), ('BIKE_SERVICE', 'Bike & Two-Wheeler Service'), ('FURNITURE_REPAIR', 'Furniture Restoration & Carpentry'), ('GAMING_REPAIR', 'Gaming Console & Controller Repair'), ('CLEANING', 'Sanitization & Deep Cleaning'), ('MAINTENANCE', 'Preventative Maintenance'), ('ELECTRONICS', 'General Electronics Repair')], max_length=40)),
                ('issue_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING_QUOTE', 'Pending Provider Quote'), ('QUOTED', 'Quote Provided (Awaiting Approval)'), ('APPROVED_IN_PROGRESS', 'Approved & In-Progress'), ('REPAIRED', 'Repaired & Ready for Inspection'), ('INSPECTED_CLOSED', 'Inspected & Closed'), ('CANCELLED', 'Cancelled')], default='PENDING_QUOTE', max_length=30)),
                ('final_quote_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('provider_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quote_notes', models.TextField(blank=True)),
                ('is_quote_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='assets.asset')),
                ('assigned_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='services.serviceprovider')),
                ('damage_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='inspections.damagereport')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
