# Generated by Django 5.2.17 on 2026-09-04 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_score', models.IntegerField(default=150, help_text='Dynamic score between 0 and 1000')),
                ('tier', models.CharField(choices=[('BRONZE', 'Bronze (New / Unverified)'), ('SILVER', 'Silver (Standard Trusted)'), ('GOLD', 'Gold (High Trust / Experienced)'), ('PLATINUM', 'Platinum (Elite Marketplace Star)')], default='SILVER', max_length=20)),
                ('completed_rentals_count', models.IntegerField(default=0)),
                ('dispute_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trust Profile',
                'verbose_name_plural': 'Trust Profiles',
            },
        ),
        migrations.CreateModel(
            name='TrustEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('KYC_VERIFIED', 'Identity / KYC Verified (+50)'), ('RENTAL_COMPLETED', 'Successful Rental Completed (+15)'), ('ON_TIME_RETURN', 'Asset Returned On-Time (+10)'), ('POSITIVE_REVIEW', 'Received 4 or 5 Star Review (+15)'), ('NEGATIVE_REVIEW', 'Received 1 or 2 Star Review (-20)'), ('LATE_RETURN', 'Late Return Incident (-15)'), ('DAMAGE_INCIDENT', 'Asset Damaged Incident (-30)'), ('DISPUTE_RAISED', 'Dispute Filed Against User (-25)')], max_length=40)),
                ('score_delta', models.IntegerField(help_text='Positive or negative score adjustment')),
                ('description', models.CharField(max_length=255)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='trust.trustprofile')),
            ],
            options={
                'verbose_name': 'Trust Event',
                'verbose_name_plural': 'Trust Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
