# Generated by Django 5.2.17 on 2026-09-04 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('PAYMENT_RECEIVED', 'Customer Payment Received'), ('SECURITY_DEPOSIT_HELD', 'Security Deposit Held (Escrow)'), ('PLATFORM_COMMISSION_EARNED', 'Platform Commission Earned'), ('PLATFORM_FEE_EARNED', 'Platform Fee Earned'), ('DELIVERY_FEE_EARNED', 'Delivery Fee Earned'), ('OWNER_PAYABLE_CREDITED', 'Owner Payable Credited'), ('OWNER_PAYOUT_SETTLED', 'Owner Payout Settled'), ('DEPOSIT_RELEASED', 'Security Deposit Released to Renter'), ('DEPOSIT_DEDUCTED', 'Security Deposit Deducted for Damage'), ('REFUND_ISSUED', 'Refund Issued to Customer')], max_length=40)),
                ('debit_account', models.CharField(choices=[('ESCROW_INFLOW', 'Escrow Clearing Inflow'), ('SECURITY_DEPOSIT_ESCROW', 'Security Deposit Escrow'), ('PLATFORM_REVENUE', 'Rentido Platform Revenue'), ('OWNER_PAYABLE', 'Owner Payable Liability'), ('RENTER_BANK_ACCOUNT', 'Renter Bank/Card'), ('OWNER_BANK_ACCOUNT', 'Owner Bank/UPI')], max_length=40)),
                ('credit_account', models.CharField(choices=[('ESCROW_INFLOW', 'Escrow Clearing Inflow'), ('SECURITY_DEPOSIT_ESCROW', 'Security Deposit Escrow'), ('PLATFORM_REVENUE', 'Rentido Platform Revenue'), ('OWNER_PAYABLE', 'Owner Payable Liability'), ('RENTER_BANK_ACCOUNT', 'Renter Bank/Card'), ('OWNER_BANK_ACCOUNT', 'Owner Bank/UPI')], max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_immutable', models.BooleanField(default=True, editable=False)),
                ('rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='rentals.rental')),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('NET_BANKING', 'Net Banking'), ('WALLET', 'Wallet'), ('MOCK_GATEWAY', 'Mock Gateway (Dev)')], default='UPI', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentals.rental')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deducted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('HELD', 'Held in Escrow'), ('RELEASED', 'Fully Released to Renter'), ('PARTIALLY_DEDUCTED', 'Partially Deducted for Damage'), ('FULLY_DEDUCTED', 'Fully Deducted'), ('DISPUTED', 'Disputed')], default='HELD', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('held_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_deposit_record', to='rentals.rental')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='held_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Deposit',
                'verbose_name_plural': 'Security Deposits',
            },
        ),
    ]
