# Generated by Django 5.2.17 on 2026-09-04 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_end_datetime', models.DateTimeField()),
                ('new_end_datetime', models.DateTimeField()),
                ('additional_rental_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_approved_by_owner', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalPricingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_rental_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('platform_commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('security_deposit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner_payout_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raw_calculation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('fulfillment_type', models.CharField(choices=[('SELF_PICKUP', 'Self Pickup'), ('DRIVER_DELIVERY', 'Driver Delivery'), ('HUB_PICKUP', 'Hub Pickup')], default='SELF_PICKUP', max_length=30)),
                ('status', models.CharField(choices=[('PAYMENT_PENDING', 'Payment Pending'), ('CONFIRMED', 'Confirmed'), ('READY_FOR_HANDOVER', 'Ready for Handover'), ('HANDOVER_IN_PROGRESS', 'Handover in Progress'), ('ACTIVE', 'Active Rental'), ('EXTENSION_PENDING', 'Extension Pending'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_IN_PROGRESS', 'Return in Progress'), ('INSPECTION_PENDING', 'Inspection Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], default='PAYMENT_PENDING', max_length=30)),
                ('handover_otp', models.CharField(blank=True, max_length=6)),
                ('return_otp', models.CharField(blank=True, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Rental',
                'verbose_name_plural': 'Rentals',
                'ordering': ['-created_at'],
            },
        ),
    ]
