# Generated by Django 5.2.17 on 2026-09-04 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals_as_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rental',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals_as_renter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalextension',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='rentals.rental'),
        ),
        migrations.AddField(
            model_name='rentalpricingsnapshot',
            name='rental',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_snapshot', to='rentals.rental'),
        ),
    ]
