# Generated by Django 5.2.17 on 2026-09-04 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalextension',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rental Extension', 'verbose_name_plural': 'Rental Extensions'},
        ),
        migrations.AddField(
            model_name='rentalextension',
            name='additional_platform_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rentalextension',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rentalextension',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rentalextension',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending Owner Approval'), ('APPROVED', 'Approved by Owner (Awaiting Payment)'), ('PAID', 'Paid & Confirmed'), ('REJECTED', 'Rejected by Owner'), ('CANCELLED', 'Cancelled')], default='PENDING_APPROVAL', max_length=30),
        ),
        migrations.AddField(
            model_name='rentalextension',
            name='total_extension_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rentalextension',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='RentalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(max_length=100, unique=True)),
                ('terms_and_conditions', models.TextField()),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='rentals.rental')),
            ],
            options={
                'verbose_name': 'Rental Agreement',
                'verbose_name_plural': 'Rental Agreements',
            },
        ),
        migrations.CreateModel(
            name='AgreementAddendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addendum_number', models.CharField(max_length=100, unique=True)),
                ('extended_until', models.DateTimeField()),
                ('additional_amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('terms_addendum', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental_extension', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addendum', to='rentals.rentalextension')),
                ('rental_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addendums', to='rentals.rentalagreement')),
            ],
            options={
                'verbose_name': 'Agreement Addendum',
                'verbose_name_plural': 'Agreement Addendums',
            },
        ),
    ]
