# Generated by Django 5.2.17 on 2026-09-04 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('PRE_RENTAL', 'Pre-Rental Verification'), ('HANDOVER', 'Handover Condition Check'), ('RETURN', 'Return Inspection'), ('POST_REPAIR', 'Post-Repair Verification')], max_length=30)),
                ('condition_grade', models.CharField(choices=[('EXCELLENT', 'Excellent / Flawless'), ('GOOD', 'Good / Minor Normal Wear'), ('FAIR', 'Fair / Noticeable Wear'), ('DAMAGED', 'Damaged / Missing Accessories')], default='GOOD', max_length=20)),
                ('checklist_answers', models.JSONField(blank=True, default=dict, help_text='Dynamic checklist items: powers_on, screen_intact, etc.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections_conducted', to=settings.AUTH_USER_MODEL)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='rentals.rental')),
            ],
            options={
                'verbose_name': 'Inspection',
                'verbose_name_plural': 'Inspections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low (Minor scratch/cosmetic)'), ('MEDIUM', 'Medium (Repairable functional defect)'), ('HIGH', 'High (Major component failure)'), ('CRITICAL', 'Critical (Total loss / irreparable)')], default='MEDIUM', max_length=20)),
                ('responsibility', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review / Assessment'), ('RENTER_RESPONSIBILITY', 'Renter Responsibility'), ('OWNER_RESPONSIBILITY', 'Owner Responsibility / Pre-existing'), ('TRANSPORT_DAMAGE', 'Transport / Logistics Damage'), ('NORMAL_WEAR', 'Normal Wear & Tear (No charge)')], default='PENDING_REVIEW', max_length=30)),
                ('estimated_repair_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('approved_deduction_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('UNDER_REVIEW', 'Under Review'), ('SETTLED', 'Settled & Deducted'), ('DISPUTED', 'Disputed to Admin')], default='REPORTED', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='rentals.rental')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage_reports_filed', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reports', to='inspections.inspection')),
            ],
            options={
                'verbose_name': 'Damage Report',
                'verbose_name_plural': 'Damage Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inspections/photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.inspection')),
            ],
        ),
    ]
