# Generated by Django 5.2.17 on 2026-09-04 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pricing_model', models.CharField(choices=[('HOURLY', 'Per Hour'), ('DAILY', 'Per Day'), ('WEEKLY', 'Per Week'), ('MONTHLY', 'Per Month')], default='DAILY', max_length=20)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0.0, help_text='Refundable security deposit held during rental', max_digits=10)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=150)),
                ('pincode', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_self_pickup_available', models.BooleanField(default=True)),
                ('is_delivery_available', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published / Active'), ('PAUSED', 'Paused by Owner'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Rental Listing',
                'verbose_name_plural': 'Rental Listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
