# Generated by Django 5.2.17 on 2026-09-04 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='assets/photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asset Media',
                'verbose_name_plural': 'Asset Media',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Sony Alpha A7 III', max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('condition', models.CharField(choices=[('NEW', 'Brand New'), ('LIKE_NEW', 'Like New'), ('GOOD', 'Good Condition'), ('FAIR', 'Fair / Functional')], default='GOOD', max_length=20)),
                ('replacement_value', models.DecimalField(decimal_places=2, help_text='Estimated replacement value in local currency', max_digits=12)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('AVAILABLE', 'Available'), ('RENTED', 'Currently Rented'), ('MAINTENANCE', 'In Maintenance / Repair'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20)),
                ('ownership_document', models.FileField(blank=True, help_text='Invoice or ownership proof', null=True, upload_to='assets/documents/')),
                ('notes', models.TextField(blank=True, help_text='Internal notes or verification remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='categories.category')),
            ],
            options={
                'verbose_name': 'Physical Asset',
                'verbose_name_plural': 'Physical Assets',
                'ordering': ['-created_at'],
            },
        ),
    ]
